POST http://localhost:8090/api/book
Content-Type: application/json

{
  "price": 15.3,
  "isbn": "121341381648 (ISBN13: 121341381648)",
  "title": "Pushing Clouds",
  "language": "English",
  "publisher": "Wepress Inc.",
  "authorId": 1,
  "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore e fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem",
  "publishedDate": "2012-04-23T18:25:43.511Z",
  "genres": [
    1,
    2,
    3,
    4
  ],
  "editionFormat": "Paperback, 450 Pages"
}

####
POST http://localhost:8090/api/author
Content-Type: application/json

{
  "lastname": "Smile",
  "firstname": "Kevin"
}


###

POST http://localhost:8090/api/genre
Content-Type: application/json

{
  "name": "Biography"
}

###
POST http://localhost:8090/api/feedback
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzdXBlckFkbWluQGFkbWluLmNvbSIsImlhdCI6MTY4NjkyODI4OSwiZXhwIjoxNjg3MDAwMjg5fQ.46uhoioaTFavVEwor-XmkSNzsunhSdArJQt6HF3Q0K-AzVM2vd8DtiB_pWVuYeaTZJy3mgtkdVXxPT9pbEwSQA

{
  "message": "asdssdsf",
  "point": 2
}


###
POST http://localhost:8090/api/v1/auth/sign-in
Content-Type: application/json

{
  "email": "superAdmin@admin.com",
  "password": "123"
}


###
GET http://localhost:8090/api/book
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzdXBlckFkbWluQGFkbWluLmNvbSIsImlhdCI6MTY4NjkyODQ1NCwiZXhwIjoxNjg3MDAwNDU0fQ.J_NhBkCZrCqsh1ZD4f79KFhFzKISczprA3OpeuFMPVn9VV_F7o_oQl4L8Jj8BXJz8P0UO2u9PS8uHfiHW7TnSA


###
GET http://localhost:8090/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3YWI0MjAxNi0xNmYwLTQ1ODYtYTM5YmEyM2ItODI3ZC00MDJlLTkzMmItODM2ZDNiOGY2ZTYyLWJlNDQtZmNiMTFlMGYyMmNhIiwiaWF0IjoxNjg3MDE0NzM2LCJleHAiOjE2ODcwODY3MzZ9.0zwGIBcmCyJ6YOhS6jtgXS3k6dlSuseBbNWs-CN_LMw