package com.example.libraryback.util;

public interface MessageConstants {
    String PHONE_NUMBER_SHOULD_NOT_BLANK = "PHONE_NUMBER_SHOULD_NOT_BLANK";
    String NAME_SHOULD_NOT_BLANK = "NAME_SHOULD_NOT_BLANK";
    String NAME_REQUIRED = "NAME_REQUIRED";
    String DEFAULT_PAGE_REQUIRED = "DEFAULT_PAGE_REQUIRED";
    String INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
    String USER_NOT_FOUND_OR_DISABLED = "USER_NOT_FOUND_OR_DISABLED";
    String LOGIN_OR_PASSWORD_ERROR = "INCORRECT EMAIL OR PASSWORD";
    String ALREADY_EXISTS = "ALREADY_EXISTS";
    String ADMIN_ROLE_CAN_NOT_BE_DELETED = "ADMIN_ROLE_CAN_NOT_BE_DELETED";
    String RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND";
    String PASSWORD_SHOULD_NOT_BLANK = "PASSWORD_SHOULD_NOT_BLANK";
    String ROLE_NOT_FOUND = "ROLE_NOT_FOUND";
    String ACCESS_TOKEN_MISSED = "ACCESS_TOKEN_MISSED";
}
